apiVersion: v1
kind: Service
metadata:
  name: {{ include "ledger.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ledger.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- with .protocol }}
      protocol: {{ . }}
      {{- end }}
    {{- end }}
