#!/bin/bash
# scripts/diagnose-fake-gcs.sh
#
# Captures fake-gcs-server's container logs DURING the diagnostic
# test run. Tells us whether a 404 is generated by our code (path
# mismatch) or by fake-gcs's handler (bug in the emulator).
#
# Output:
#   /tmp/fake-gcs-diag.log     full container log
#   /tmp/fake-gcs-diag-test.log  go test output

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_FILE="${REPO_ROOT}/integration/docker-compose.yml"

cd "${REPO_ROOT}"

echo "== teardown + clean bring-up =="
docker compose -f "${COMPOSE_FILE}" down -v 2>/dev/null || true
docker compose -f "${COMPOSE_FILE}" up -d

# Wait for fake-gcs healthy.
for i in $(seq 1 60); do
    health="$(docker inspect --format='{{.State.Health.Status}}' ortholog_test_gcs 2>/dev/null || true)"
    if [ "${health}" = "healthy" ]; then
        echo "fake-gcs healthy (attempt ${i})"
        break
    fi
    sleep 1
done

# Wait for host port reachability.
for i in $(seq 1 60); do
    if nc -z 127.0.0.1 4443 2>/dev/null; then break; fi
    sleep 1
done

echo "== fake-gcs version + image =="
IMAGE_NAME="$(docker inspect --format='{{.Config.Image}}' ortholog_test_gcs)"
IMAGE_DIGEST="$(docker inspect --format='{{index .Image}}' ortholog_test_gcs)"
echo "  image:  ${IMAGE_NAME}"
echo "  digest: ${IMAGE_DIGEST}"
docker exec ortholog_test_gcs /bin/fake-gcs-server -h 2>&1 | head -3 || \
    echo "  (couldn't probe binary version)"

# Ensure test bucket exists.
HTTP_CODE="$(curl -s -o /dev/null -w "%{http_code}" \
    -X POST -H "Content-Type: application/json" \
    -d '{"name":"ortholog-test-bytes"}' \
    "http://127.0.0.1:4443/storage/v1/b" || true)"
echo "== test bucket: status=${HTTP_CODE} =="

echo "== starting fake-gcs log capture (background) =="
docker logs -f ortholog_test_gcs > /tmp/fake-gcs-diag.log 2>&1 &
LOG_PID=$!
trap "kill ${LOG_PID} 2>/dev/null || true" EXIT

# Snapshot log line count BEFORE the test so we can show only the
# during-test slice afterwards.
sleep 0.3  # let logger flush any startup chatter
LOG_START_LINES="$(wc -l < /tmp/fake-gcs-diag.log 2>/dev/null || echo 0)"
LOG_START_LINES="$(echo "${LOG_START_LINES}" | tr -d ' ')"
echo "  log baseline: ${LOG_START_LINES} lines"

export ORTHOLOG_TEST_GCS_ENDPOINT='http://127.0.0.1:4443/storage/v1/'
export ORTHOLOG_TEST_GCS_BUCKET='ortholog-test-bytes'

echo
echo "== running diagnostic tests (E1-E5) =="
go test -v -count=1 -timeout=120s \
    -run 'TestFakeGCS_Diagnostic' \
    ./tessera/ 2>&1 | tee /tmp/fake-gcs-diag-test.log || true

# Let the log file flush.
sleep 1

LOG_END_LINES="$(wc -l < /tmp/fake-gcs-diag.log 2>/dev/null || echo 0)"
LOG_END_LINES="$(echo "${LOG_END_LINES}" | tr -d ' ')"

echo
echo "== fake-gcs container log slice for the test window =="
echo "   (lines ${LOG_START_LINES}..${LOG_END_LINES})"
echo

START_PLUS_ONE=$((LOG_START_LINES + 1))
sed -n "${START_PLUS_ONE},${LOG_END_LINES}p" /tmp/fake-gcs-diag.log | \
    grep -E "(GET|PUT|POST|DELETE|404|405|500|error|ERROR|warning|WARNING)" || \
    echo "(no relevant lines — fake-gcs may not log requests at this verbosity)"

echo
echo "== full logs saved to: =="
echo "   /tmp/fake-gcs-diag.log       (entire fake-gcs container log)"
echo "   /tmp/fake-gcs-diag-test.log  (go test output)"
echo
echo "== to inspect specific 404s with their object paths: =="
echo "   grep -E '404|GET' /tmp/fake-gcs-diag.log | head -50"
echo
echo "== to tear down: =="
echo "   docker compose -f integration/docker-compose.yml down -v"
